version: '3'
services:

  sps-game:
    build: ./docker
    container_name: sps-game
    restart: always
    tty: true
    working_dir: /var/www/html
    networks:
      - sps-game-network
    volumes:
      - ./:/var/www/html

networks:
  sps-game-network:
    driver: bridge